[features]
seeds = false
skip-lint = false
[programs.localnet]
roundie_to_round = "C33wP7zndt1MrsGfGnJ91HT6B7rNZdmMASYvmcoRudNm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/paulbredenberg/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
