[features]
seeds = false
skip-lint = false
[programs.localnet]
roundie_to_round = "HgpmQVLjipSFXipjqfjkX2LLKRc8nKBktuEXjpeAqqbe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://frosty-thrilling-sun.solana-devnet.discover.quiknode.pro/2f4f7bd5b15f565bdf2b069e1700be4ea9d489ce/"
wallet = "/Users/paulbredenberg/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
